version: '2'

services:
  {% for client_name, params in clients.items() %}
  {{client_name}}:
    image: ubuntu
    privileged: true
    container_name: {{client_name}}
    command: /bin/bash -c "
      route del default;
      route add default gw {{ params['gateway'] }} eth0;
      route;

      rsyslogd;
      tail -f /var/log/syslog"
    networks:
      {{ params['network'] }}:
        ipv4_address: {{ params['ip'] }}
  {% endfor %}

  {% for router_name, params in routers.items() %}
  {{router_name}}:
    container_name: {{router_name}}
    image: higebu/vyos
    privileged: true
    volumes:
      - .:/injected
    command: sbin/init
    networks:
    # addresses are set here only in order to make sure they will be available
    # (true address assignment is done by injected config.boot file)
    {% for network_name, network_params in params['networks'].items() %}
      {{network_name}}:
        ipv4_address: {{network_params['ipv4']}}
    {% endfor %}
  {% endfor %}

networks:
  lan10:
    ipam:
      config:
      - subnet: 10.1.0.0/16
        # default gateway will be overridden
        # as it is bridged to the internet
        gateway: 10.1.0.254
  lan9:
    ipam:
      config:
      - subnet: 9.1.0.0/16
        gateway: 9.1.0.254
  lan8:
    ipam:
      config:
      - subnet: 8.1.0.0/16
        gateway: 8.1.0.254
  lan7:
    ipam:
      config:
      - subnet: 7.1.0.0/16
        gateway: 7.1.0.254
