version: '2'
services:
  web:
    build: .
    privileged: true
    volumes:
      - .:/code #remove on Windows if having 'cannot find manage.py' problems
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:80"